### ISSUE TITLE
Recolor 2.5 throws error on Anki 2.1.54 on MacOS

### ISSUE THREAD

**Issue by wrinkledeth** [AnKing-Memberships/AnkiRecolor#28]
Running on:  MacOS Ventura on M2 Air 

Anki Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

After upgrading to recolor 2.5, i am getting the following error when starting Anki:  

```bash
When loading '⁨ReColor⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/user/Library/Application Support/Anki2/addons21/688199788/__init__.py", line 7, in <module>
    from . import colors
  File "/Users/user/Library/Application Support/Anki2/addons21/688199788/colors.py", line 205, in <module>
    recolor_python()
  File "/Users/user/Library/Application Support/Anki2/addons21/688199788/colors.py", line 22, in recolor_python
    replace_color(color_entries, color_name)
  File "/Users/user/Library/Application Support/Anki2/addons21/688199788/colors.py", line 41, in replace_color
    anki_color["light"] = color_entry[1]
TypeError: 'tuple' object does not support item assignment
⁩
```

**Comment by AnKingMed** [comment]
This should be resolved now
