### ISSUE TITLE
Recolor update error again on linux

### ISSUE THREAD

**Issue by shoaib281** [AnKing-Memberships/AnkiRecolor#31]
I faced the same error as [here](https://github.com/AnKing-Memberships/AnkiRecolor/issues/28). I updated my extension and now I'm facing a new error.

Anki Version ⁨2.1.53
Python 3.9.10 Qt 6.3.0 PyQt 6.3.0
OS: Kubuntu

Upon opening anki:
```py
When loading '⁨ReColor⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/home/user/.local/share/Anki2/addons21/688199788/__init__.py", line 2, in <module>
    from . import colors
  File "/home/user/.local/share/Anki2/addons21/688199788/colors.py", line 198, in <module>
    recolor_python()
  File "/home/user/.local/share/Anki2/addons21/688199788/colors.py", line 51, in recolor_python
    apply_palette()
  File "/home/user/.local/share/Anki2/addons21/688199788/colors.py", line 84, in apply_palette
    palette.setColor(role, qcolor(conf_key))
  File "/home/user/.local/share/Anki2/addons21/688199788/colors.py", line 60, in qcolor
    return QColor(hex_color)
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'NoneType'
  QColor(int): too many arguments
  QColor(QRgba64): argument 1 has unexpected type 'NoneType'
  QColor(Any): argument 1 has unexpected type 'NoneType'
  QColor(): argument 1 has unexpected type 'NoneType'
```

**Comment by AnKingMed** [comment]
Are you still having this issue? Sorry for the delay in responding

**Comment by BlueGreenMagick** [comment]
You may need to reset add-on config.
